# Generated by Django 3.0.5 on 2020-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_mentee', models.CharField(max_length=100)),
                ('nama_mentee', models.CharField(max_length=100)),
                ('pesan_mentee', models.TextField()),
            ],
        ),
    ]
