# Generated by Django 3.0.5 on 2020-04-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200414_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jualproduk',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jualproduk',
            name='image',
        ),
    ]
