# Generated by Django 3.0.5 on 2020-04-14 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200414_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='jualproduk',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jualproduk',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jualproduk',
            name='location',
            field=models.CharField(default=-1.0, max_length=100),
            preserve_default=False,
        ),
    ]
