# Generated by Django 3.0.5 on 2020-04-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200414_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='jualproduk',
            name='kategori_id',
            field=models.CharField(default=-1.0, max_length=100),
            preserve_default=False,
        ),
    ]
